### ISSUE TITLE
When import the "react-component-lib",show the err of the React is undefied.

### ISSUE THREAD

**Issue by chenpeng2** [cd-fe/react-component#65]
Uncaught ReferenceError: React is not defined
    at Object.e.exports.toggleValues (http://localhost:8080/src/bundle.js:29915:7656)
    at A (http://localhost:8080/src/bundle.js:29915:777)
    at Object.e.exports.__timer (http://localhost:8080/src/bundle.js:29915:17719)
    at A (http://localhost:8080/src/bundle.js:29915:777)
    at Object.e.__esModule.default (http://localhost:8080/src/bundle.js:29915:966)
    at A (http://localhost:8080/src/bundle.js:29915:777)
    at e.__esModule.default (http://localhost:8080/src/bundle.js:29915:864)
    at http://localhost:8080/src/bundle.js:29915:869
    at e.A.t.(anonymous function).exports (http://localhost:8080/src/bundle.js:29915:38)
    at Object.<anonymous> (http://localhost:8080/src/bundle.js:29915:521)

**Comment by darkty2009** [comment]
react太大，就没有放在库里，需在外部通过 script 方式提前引入
